# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 17:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='professor_matricula',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Digite um número de matricula válido')]),
        ),
    ]
